[package]
name = "syscall-num-name"
version = "0.1.0"
authors = ["Chethan Suresh <Chethan.Suresh@sony.com>"]
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
libseccomp = "0.1.0"