[package]
name = "syscall-num-name"
license = "MIT"
version = "0.1.0"
description = "Get all mapping of syscall number to name using libseccomp-rs"
authors = ["Chethan Suresh <Chethan.Suresh@sony.com>"]
edition = "2021"

[dependencies]
libseccomp = "0.1.3"
